// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (title, description, completed) VALUES ($1, $2, $3) RETURNING id
`

type CreateTodoParams struct {
	Title       string
	Description pgtype.Text
	Completed   pgtype.Bool
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.Title, arg.Description, arg.Completed)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password) VALUES ($1, $2, $3) RETURNING id
`

type CreateUserParams struct {
	Name     string
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.Password)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createUserTodo = `-- name: CreateUserTodo :one
INSERT INTO user_todos (user_id, todo_id) VALUES ($1, $2) RETURNING todo_id
`

type CreateUserTodoParams struct {
	UserID int32
	TodoID int32
}

func (q *Queries) CreateUserTodo(ctx context.Context, arg CreateUserTodoParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUserTodo, arg.UserID, arg.TodoID)
	var todo_id int32
	err := row.Scan(&todo_id)
	return todo_id, err
}

const deleteTodo = `-- name: DeleteTodo :one
DELETE FROM todos WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteTodo(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteTodo, id)
	err := row.Scan(&id)
	return id, err
}

const deleteUserTodo = `-- name: DeleteUserTodo :one
DELETE FROM user_todos WHERE user_id = $1 AND todo_id = $2 RETURNING todo_id
`

type DeleteUserTodoParams struct {
	UserID int32
	TodoID int32
}

func (q *Queries) DeleteUserTodo(ctx context.Context, arg DeleteUserTodoParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteUserTodo, arg.UserID, arg.TodoID)
	var todo_id int32
	err := row.Scan(&todo_id)
	return todo_id, err
}

const getTodo = `-- name: GetTodo :one
SELECT id, title, description, completed, created_at, updated_at FROM todos WHERE id = $1
`

func (q *Queries) GetTodo(ctx context.Context, id int32) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodoUsers = `-- name: GetTodoUsers :many
SELECT user_id, todo_id FROM user_todos WHERE todo_id = $1
`

func (q *Queries) GetTodoUsers(ctx context.Context, todoID int32) ([]UserTodo, error) {
	rows, err := q.db.Query(ctx, getTodoUsers, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserTodo
	for rows.Next() {
		var i UserTodo
		if err := rows.Scan(&i.UserID, &i.TodoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodos = `-- name: GetTodos :many
SELECT id, title, description, completed, created_at, updated_at FROM todos
`

func (q *Queries) GetTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, password FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, email, password FROM users WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const getUserTodo = `-- name: GetUserTodo :one
SELECT user_id, todo_id FROM user_todos WHERE user_id = $1 AND todo_id = $2
`

type GetUserTodoParams struct {
	UserID int32
	TodoID int32
}

func (q *Queries) GetUserTodo(ctx context.Context, arg GetUserTodoParams) (UserTodo, error) {
	row := q.db.QueryRow(ctx, getUserTodo, arg.UserID, arg.TodoID)
	var i UserTodo
	err := row.Scan(&i.UserID, &i.TodoID)
	return i, err
}

const getUserTodos = `-- name: GetUserTodos :many
SELECT user_id, todo_id FROM user_todos WHERE user_id = $1
`

func (q *Queries) GetUserTodos(ctx context.Context, userID int32) ([]UserTodo, error) {
	rows, err := q.db.Query(ctx, getUserTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserTodo
	for rows.Next() {
		var i UserTodo
		if err := rows.Scan(&i.UserID, &i.TodoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos SET title = $1, description = $2, completed = $3 WHERE id = $4 RETURNING id
`

type UpdateTodoParams struct {
	Title       string
	Description pgtype.Text
	Completed   pgtype.Bool
	ID          int32
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.ID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
